apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "argocd-custom-exporter.fullname" . }}
  labels:
    {{- include "argocd-custom-exporter.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ quote $value }}
    {{- end }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "argocd-custom-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: {{ .Values.serviceMonitor.path }}
    scheme: {{ .Values.serviceMonitor.scheme }}
    interval: {{ .Values.serviceMonitor.interval }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
