name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

#      - name: Extract Helm chart version
#        id: get_chart_version
#        run: |
#          CHART_VERSION=$(grep 'version:' path-to-your-chart/Chart.yaml | awk '{print $2}')
#          echo "Chart version is $CHART_VERSION"
#          echo "::set-output name=CHART_VERSION::$CHART_VERSION"


      - name: Determine next version
        id: get_version
        run: |
          CURRENT_VERSION=$(grep 'version:' chart/Chart.yaml | awk '{print $2}')
          # Assuming semantic versioning and just incrementing patch version
          MAJOR_VERSION=$(echo $CURRENT_VERSION | cut -d. -f1)
          MINOR_VERSION=$(echo $CURRENT_VERSION | cut -d. -f2)
          PATCH_VERSION=$(echo $CURRENT_VERSION | cut -d. -f3)
          NEXT_PATCH_VERSION=$((PATCH_VERSION + 1))
          NEXT_VERSION="$MAJOR_VERSION.$MINOR_VERSION.$NEXT_PATCH_VERSION"
          echo "Next version is $NEXT_VERSION"
          echo "::set-output name=VERSION::$NEXT_VERSION"

      - name: Update Helm chart version
        run: |
        sed -i "s/version: .*/version: ${{ steps.get_version.outputs.VERSION }}/" chart/Chart.yaml


      # Build and push Docker image
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tags: bakithesnake/argocd-custom-exporter:latest, bakithesnake/argocd-custom-exporter:${{ steps.get_chart_version.outputs.CHART_VERSION }}


      # Package Helm chart with the new version
      - name: Package Helm Chart
        run: |
          helm package path-to-your-chart-directory

      # Helm repo index
      - name: Update Helm repo index
        run: |
          helm repo index --url "https://raw.githubusercontent.com/free-devops/argocd-custom-exporter/main/" --merge index.yaml .
          helm repo index .

      # Push changes back to GitHub
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update Helm chart and repo index"
          git push

      # NOTE: For pushing back to GitHub, you'd likely need a PAT (Personal Access Token) to handle authentication.
